

objs += \
	  $(ROOT)/cpu/$(CPU)/app_timer.o \
	  $(ROOT)/cpu/$(CPU)/setup.o \
	  $(ROOT)/cpu/$(CPU)/adc_api.o \
	  $(ROOT)/cpu/$(CPU)/pwm_led.o \
	  $(ROOT)/cpu/$(CPU)/iic_hw.o \
	  $(ROOT)/cpu/$(CPU)/iic_soft.o \
	  $(ROOT)/cpu/$(CPU)/irflt.o \
	  $(ROOT)/cpu/$(CPU)/uart_dev.o \
	  $(ROOT)/cpu/$(CPU)/spi.o \
	  $(ROOT)/cpu/$(CPU)/mcpwm.o \
	  $(ROOT)/cpu/$(CPU)/plcnt.o \
	  $(ROOT)/cpu/$(CPU)/charge.o \
	  $(ROOT)/cpu/$(CPU)/chargestore.o \
	  # $(ROOT)/cpu/$(CPU)/plnk.o \


objs += \
	  $(ROOT)/cpu/$(CPU)/uart_test.o \
	  $(ROOT)/cpu/$(CPU)/spi_test.o \
	  $(ROOT)/cpu/$(CPU)/iic_eeprom_test.o \
	  $(ROOT)/cpu/$(CPU)/iic_slave_test.o \


