

ifeq ($(APP_CASE),soundbox)

includes += \
	-I$(ROOT)/cpu/$(CPU)/audio_mic/ \

objs += \
	  $(ROOT)/cpu/$(CPU)/audio_mic/loud_speaker.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/effect_cfg.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/effect_tool.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/effect_reg.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/effect_debug.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/effect_reg_echo.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/effect_reg_reverb.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/mic_stream.o \
	  $(ROOT)/cpu/$(CPU)/audio_mic/mic_effect.o \

endif

