
LIBS = \
--start-group \
   $(AR_DIR)/cpu.a \
   $(AR_DIR)/system.a \
   $(AR_DIR)/btctrler.a \
   $(AR_DIR)/btstack.a \
   $(AR_DIR)/update.a \
   $(AR_DIR)/crypto_toolbox_Osize.a \
   $(AR_DIR)/rcsp_stack.a \
   $(AR_DIR)/agreement.a \
--end-group

objs += \
	  $(ROOT)/apps/$(APP_CASE)/board/$(CPU)/board_ac630x_demo.o \
	  $(ROOT)/apps/$(APP_CASE)/board/$(CPU)/board_ac6311_demo.o \
	  $(ROOT)/apps/$(APP_CASE)/board/$(CPU)/board_ac6313_demo.o \
	  $(ROOT)/apps/$(APP_CASE)/board/$(CPU)/board_ac6318_demo.o \
	  $(ROOT)/apps/$(APP_CASE)/board/$(CPU)/board_ac6319_demo.o \
