
export includes += \
-I$(ROOT)/include_lib  \
-I$(ROOT)/include_lib/driver/ \
-I$(ROOT)/include_lib/driver/device \
-I$(ROOT)/include_lib/driver/cpu/$(CPU) \
-I$(ROOT)/include_lib/system \
-I$(ROOT)/include_lib/system/generic  \
-I$(ROOT)/include_lib/system/device \
-I$(ROOT)/include_lib/system/fs \
-I$(ROOT)/include_lib/system/ui \
-I$(ROOT)/include_lib/btctrler \
-I$(ROOT)/include_lib/btctrler/port/$(CPU) \
-I$(ROOT)/include_lib/update \
-I$(ROOT)/include_lib/agreement \
-I$(ROOT)/include_lib/btstack/third_party/common \


ifeq ($(THIRD_PARTY_PROFILE_ENABLE),y)
includes += \
-I$(ROOT)/include_lib/btstack/third_party/rcsp/ \

else

includes += \
-I$(ROOT)/include_lib/ai_stack \
-I$(ROOT)/include_lib/ai_stack/JL_rcsp \

endif

ifeq ($(MEDIA_NEW_ENABLE),y)
includes += \
-I$(ROOT)/include_lib/media/media_new \
-I$(ROOT)/include_lib/media/media_new/media \
-I$(ROOT)/include_lib/media/media_new/media/cpu/$(CPU) \
-I$(ROOT)/include_lib/media/media_new/media/cpu/$(CPU)/asm \

else ifeq ($(MEDIA_NEW_ENABLE),d)
includes += \
-I$(ROOT)/include_lib/media/media_develop \
-I$(ROOT)/include_lib/media/media_develop/media \
-I$(ROOT)/include_lib/media/media_develop/media/cpu/$(CPU) \
-I$(ROOT)/include_lib/media/media_develop/media/cpu/$(CPU)/asm \

else #ifeq ($(MEDIA_NEW_ENABLE),y)

includes += \
-I$(ROOT)/include_lib/media/media_origin \
-I$(ROOT)/include_lib/media/media_origin/media \
-I$(ROOT)/include_lib/media/media_origin/media/cpu/$(CPU) \
-I$(ROOT)/include_lib/media/media_origin/media/cpu/$(CPU)/asm \
-I$(ROOT)/include_lib/media/media_origin/media/aec \

endif #ifeq ($(MEDIA_NEW_ENABLE),y)

