
objs += \

ifeq ($(APP_CASE),earphone)
objs += \

else ifeq ($(APP_CASE),soundbox)
objs += \
	  $(ROOT)/cpu/$(CPU)/localtws/localtws.o \
	  $(ROOT)/cpu/$(CPU)/localtws/localtws_dec.o \

else ifeq ($(APP_CASE),dongle)
objs += \

endif
