#ifndef __FEATURE_CORRECT_H__
#define __FEATURE_CORRECT_H__

#define BT_MESH_FEAT_SUPPORTED              BT_MESH_FEAT_SUPPORTED_TEMP

#if BT_MESH_FEATURES_GET(BT_MESH_FEAT_FRIEND) & BT_MESH_FEATURES_GET(BT_MESH_FEAT_LOW_POWER)
#error " error: Friend and LPN feature can't exist in the same node !!!"
#endif

#if BT_MESH_FEATURES_GET(BT_MESH_FEAT_LOW_POWER) & BT_MESH_FEATURES_GET(BT_MESH_FEAT_RELAY)
#undef  BT_MESH_FEAT_SUPPORTED
#define BT_MESH_FEAT_SUPPORTED              (BT_MESH_FEAT_SUPPORTED_TEMP & (~BT_MESH_FEAT_RELAY))
#endif

#endif /* __FEATURE_CORRECT_H__ */
