
objs += \

ifeq ($(APP_CASE),earphone)
objs += \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_file.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_fm.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_linein.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_local_tws.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_pc.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_spdif.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_sync.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/tone_player.o \

else ifeq ($(APP_CASE),soundbox)
objs += \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_bt.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_file.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_midi_file.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_fm.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_linein.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_pc.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_spdif.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_sync.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_usb_mic.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/tone_player.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_tone.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_record.o \

else ifeq ($(APP_CASE),dongle)
objs += \

else ifeq ($(APP_CASE),bt_udisk)
objs += \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_bt.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_file.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_midi_file.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_fm.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_linein.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_pc.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_spdif.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_sync.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_usb_mic.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/tone_player.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_tone.o \
	  $(ROOT)/cpu/$(CPU)/audio_dec/audio_dec_record.o \


endif
