



objs += \
	  $(ROOT)/cpu/$(CPU)/ui_driver/ui_common.o \
	  $(ROOT)/cpu/$(CPU)/ui_driver/led7/led7_driver.o \
	  $(ROOT)/cpu/$(CPU)/ui_driver/lcd_seg/lcd_seg3x9_driver.o \
	  $(ROOT)/cpu/$(CPU)/ui_driver/LED_1888/LED1888.o \
	  $(ROOT)/cpu/$(CPU)/ui_driver/led7_timer.o \

ifeq ($(APP_CASE),soundbox)
objs += \
	  $(ROOT)/cpu/$(CPU)/ui_driver/interface/ui_platform.o \
	  $(ROOT)/cpu/$(CPU)/ui_driver/lcd_spi/spi_oled.o \
	  $(ROOT)/cpu/$(CPU)/ui_driver/lcd_spi/lcd_drive.o \



endif
