

objs += \
	  $(ROOT)/cpu/$(CPU)/ui_driver/ui_common.o \
	  $(ROOT)/cpu/$(CPU)/ui_driver/led7/led7_driver.o \
	  $(ROOT)/cpu/$(CPU)/ui_driver/lcd_seg/lcd_seg3x9_driver.o \
	  $(ROOT)/cpu/$(CPU)/ui_driver/LED_1888/LED1888.o \

